### ISSUE TITLE
Error after reviewing

### ISSUE THREAD

**Issue by Synapse203** [RuzuStudios/ruzu-pop-ups#12]
Hi !
I'm posting here to report a bug but I'm not expecting you to fix it or anything, I'm running quite a lot of addons and I chose not to update to 2.1.50 so it's likely a problem on my side. 

> Debug info:
> Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
> Platform: Windows 10
> Flags: frz=True ao=True sv=3
> Add-ons, last update check: 2023-01-12 13:37:03
> 
> Caught exception:
> Traceback (most recent call last):
>   File "aqt\taskman.py", line 101, in _on_closures_pending
>   File "aqt\taskman.py", line 71, in <lambda>
>   File "aqt\taskman.py", line 90, in wrapped_done
>   File "aqt\operations\__init__.py", line 112, in wrapped_done
>   File "aqt\reviewer.py", line 414, in after_answer
>   File "aqt\reviewer.py", line 427, in _after_answering
> AttributeError: 'NoneType' object has no attribute 'id'
>

It might be a conflict with Advanced review bottom bar, review hotmouse or Progress bar original maybe ?

The error happens right after I answer the card : a loading popup appears (similar to the sync progress popup) then the error pops up. When going in the browser the review seems to have worked though. 

Other than that the addons seems great and it seems to work for other people, I love the idea ! 
Have a nice day

**Comment by CharlesHenry** [comment]
Hello @Synapse203 thanks for raising the issue. This may or may not be a bug with Anki but as you suspected, I won't be looking into this as it relates to an older version of the plugin. The current / latest version of the plugin that is being maintained is compatible with Anki 2.1.50-2.1.55+, you'd need to upgrade Anki to be able to install the newest version of the plugin from the Anki UI.
